# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jre
    wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.tgz
    tar -xvzf apache-jmeter-5.4.1.tgz
    export JMETER_HOME=$(pwd)/apache-jmeter-5.4.1
    export PATH=$PATH:$JMETER_HOME/bin
  displayName: 'Install JMeter'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build .NET Application'

- script: |
    dotnet run --project path/to/your/project.csproj --configuration $(buildConfiguration) &
    sleep 30
  displayName: 'Start .NET Application'

- script: |
    jmeter -n -t path/to/your/test-plan.jmx -l path/to/your/results.jtl
  displayName: 'Run JMeter tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/results.jtl'
    testRunTitle: 'JMeter Load Test Results'


    

